application/urls.py
from django.urls import path

from . import views

app_name = 'application'

urlpatterns = [
    path('', views.index),
    path('index.html', views.index, name='index'),
    path('application/<int:app_id>/', views.application_detail, name='app_detail'),
    path('create/', views.application_create, name='app_create'),
    path('app/<int:app_id>/delete/', views.application_delete, name='app_delete'),
    path('create_deals/', views.bitrix_deals, name='create_deals'),
    path('products/', views.ProductListView.as_view(), name='product-list'),

]

config/urls.py
from django.urls import path, include

from config import settings
from application.admin import bot_admin
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('admin/', bot_admin.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('', include('application.urls', namespace='application')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, \
    LoginView, PasswordChangeDoneView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy

from users.forms import CustomLoginForm

from . import views
from .views import CustomPasswordResetView

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(
        template_name='users/logged_out.html'), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change_form.html',
        success_url=reverse_lazy('users:password_change_done')),
         name='password_change_form'),
    path('login/', LoginView.as_view(
        template_name='users/login.html',
        authentication_form=CustomLoginForm
        ),
         name='login'
         ),
    path('password_reset/', CustomPasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        success_url=reverse_lazy('users:password_reset_done')
    ),
         name='password_reset_form'
         ),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
         name='password_change_done'
         ),
    path('password_rest/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
         name='password_reset_done'
         ),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy(
            'users:password_reset_complete')),
         name='password_reset_confirm'
         ),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
         name='password_reset_complete'
         ),
]

application/models.py
from django.core.files.storage import default_storage
from django.db import models
from django.utils.safestring import mark_safe

from application.utils import validate_phone
from users.models import CustomUser


class DeletableFileModel(models.Model):
    class Meta:
        abstract = True

    def delete(self, *args, **kwargs):
        for field in self._meta.fields:
            if isinstance(field, models.FileField) or isinstance(field, models.ImageField):
                field_value = getattr(self, field.name)
                if field_value and default_storage.exists(field_value.name):
                    default_storage.delete(field_value.name)
        super().delete(*args, **kwargs)


class Product(DeletableFileModel):
    name = models.CharField(
        verbose_name='Название продукта',
        max_length=250
    )
    description = models.TextField(
        verbose_name='Описание',
        null=True,
        blank=True
    )
    unit = models.CharField(
        verbose_name='Единица измерения',
        choices=(
            ('шт', 'шт'),
            ('кв', 'кв'),
            ('пог.м', 'пог.м'),
        ),
        max_length=10
    )
    price = models.FloatField(
        verbose_name='Цена'
    )
    photo = models.ImageField(
        upload_to='photo',
        verbose_name='Фото',
    )

    def image_tag(self):
        return mark_safe(f'<img src="{self.photo.url}" width="50"/>')

    class Meta:
        verbose_name = 'Продукты'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return f"{self.name} {self.price} руб./{self.unit}"


class Provider(models.Model):
    name = models.CharField(
        verbose_name='Название',
        max_length=150
    )
    address = models.TextField(
        verbose_name='Адрес'
    )
    full_name = models.CharField(
        verbose_name='ФИО',
        max_length=100
    )
    phone_number = models.CharField(
        verbose_name='Номер телефона',
        validators=[validate_phone],
        help_text='Введите номер телефона в формате +7 977 900 00 00',
        max_length=20
    )

    class Meta:
        verbose_name = 'Поставщик'
        verbose_name_plural = 'Поставщик'

    def __str__(self):
        return f'{self.name} {self.name} {self.phone_number}'


class Application(models.Model):
    status_choices = (
        ('Создан', 'Создан'),
        ('На производстве', 'На производстве'),
        ('Упаковка', 'Упаковка'),
        ('Готов к отгрузке', 'Готов к отгрузке'),
        ('Готов', 'Готов'),
    )
    products = models.ManyToManyField(
        Product,
        through='ApplicationProduct',
        related_name='applications'
    )
    user = models.ForeignKey(
        CustomUser,
        verbose_name='Заказчик',
        on_delete=models.SET_NULL,
        related_name='applications',
        blank=True,
        null=True
    )
    full_name = models.CharField(
        verbose_name='ФИО менеджера',
        max_length=100
    )
    phone_number = models.CharField(
        verbose_name='Номер телефона менеджера',
        validators=[validate_phone],
        help_text='Введите номер телефона в формате +7 977 900 00 00',
        max_length=20
    )
    address = models.TextField(
        verbose_name='Адрес доставки',
    )
    status = models.CharField(
        verbose_name='Статус работы',
        max_length=50,
        default='Создан',
        choices=status_choices
    )
    notes = models.TextField(
        verbose_name='Примечание',
        blank=True,
        null=True
    )
    provider = models.ForeignKey(
        Provider,
        on_delete=models.SET_NULL,
        related_name='applications',
        blank=True,
        null=True,
        verbose_name='Поставщик'
    )
    total_cost = models.FloatField(
        verbose_name='Итоговая стоимость',
        blank=True,
        null=True
    )
    manager = models.ForeignKey(
        CustomUser,
        verbose_name='Менеджер',
        on_delete=models.SET_NULL,
        related_name='manage_app',
        blank=True,
        null=True
    )
    overdue = models.BooleanField(
        verbose_name='Просрочено или нет',
        default=False
    )
    production_time = models.DateField(
        verbose_name='Сроки изготовления',
        blank=True,
        null=True
    )
    created = models.DateTimeField(
        'Дата создания',
        auto_now_add=True
    )
    updated = models.DateTimeField(
        auto_now=True,
        verbose_name="Дата изменения"
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заявки'
        verbose_name_plural = 'Заявки'

    def __str__(self):
        return str(self.pk)


class ApplicationProduct(DeletableFileModel):
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/', verbose_name='Образец')
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        verbose_name='Товар'
    )
    warehouse = models.CharField(
        verbose_name='Склад',
        max_length=100
    )
    city = models.CharField(
        verbose_name='Город',
        max_length=100
    )
    quantity = models.FloatField(
        verbose_name='Количество'
    )

    def photo_tag(self):
        return mark_safe(f'<a href="{self.image.url}"><img src="{self.image.url}" width="100"/></a>')

    photo_tag.short_description = 'Образец'


class ProductWarehouse(models.Model):
    product = models.ForeignKey(
        Product,
        verbose_name='Продукт',
        on_delete=models.CASCADE,
        related_name='stock'
    )
    warehouse = models.CharField(
        verbose_name='Склад',
        max_length=100
    )
    city = models.CharField(
        verbose_name='Город',
        max_length=100
    )
    in_stock = models.FloatField(
        verbose_name='Остаток'
    )

    class Meta:
        verbose_name = 'Остатки'
        verbose_name_plural = 'Остатки'

    def __str__(self):
        if self.in_stock == 0:
            return f"{self.product.name} {self.product.price} руб./{self.product.unit} (ПОД ЗАКАЗ)"
        return (f"{self.product.name} {self.product.price} руб./{self.product.unit} {self.city} {self.warehouse} "
                f"Остаток: {self.in_stock} {self.product.unit}")


class Objects(models.Model):
    user = models.ForeignKey(
        CustomUser,
        verbose_name='Пользователь',
        on_delete=models.SET_NULL,
        related_name='objects',
        blank=True,
        null=True
    )
    city = models.CharField(
        verbose_name='Населенный пункт местонахождения объекта (город, поселок, станица и др.)',
        max_length=100
    )
    street = models.CharField(
        verbose_name='Улица местонахождения объекта',
        max_length=100
    )
    house = models.CharField(
        verbose_name='Дом местонахождения объекта',
        max_length=100
    )
    dealer_name = models.CharField(
        verbose_name='Наименование дилера',
        max_length=100
    )
    manager = models.CharField(
        verbose_name='Менеджер от дилера (ФИО И номер телефона)',
        max_length=100
    )
    main_name = models.CharField(
        verbose_name='ФИО, должность контактного лица с которым '
                     'ведутся переговоры',
        max_length=100
    )
    main_phone = models.CharField(
        verbose_name='Телефон контактного лица (Полностью без сокращений)',
        max_length=100
    )
    full_address = models.CharField(
        verbose_name='Полный адрес',
        max_length=255
    )
    full_name_object = models.CharField(
        verbose_name='Полное наименование объекта',
        max_length=100
    )
    architect = models.CharField(
        verbose_name='Архитектор/ аритектурная организация',
        max_length=100
    )
    investor = models.CharField(
        verbose_name='Инвестор/ застройщик',
        max_length=100
    )
    materials = models.CharField(
        verbose_name='Конкурирующие материалы',
        max_length=100
    )
    stages = models.CharField(
        verbose_name='Стадии реализации проекта',
        max_length=100
    )
    date_of_delivery = models.DateField(
        verbose_name='Дата поставки'
    )
    document = models.FileField(
        upload_to='document',
        verbose_name='Титульный лист/Или визуализация проекта',
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = 'Объекты'
        verbose_name_plural = 'Объекты'

    def __str__(self):
        return self.full_name_object

application/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404

from config import settings
from application.forms import ApplicationForm, ObjectsForm
from application.models import (
    Application,
    ApplicationProduct,
    ProductWarehouse,
    Product
)
from application.utils import check_deals_address, create_deals

from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin



@login_required
def index(request):
    template = 'application/index.html'
    title = 'Это главная страница'
    paginator = Paginator(request.user.applications.all(), settings.PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': title,
        'page_obj': page_obj
    }

    return render(request, template, context)


@login_required
def application_create(request):
    if request.method == 'POST':
        form = ApplicationForm(request.POST)
        if form.is_valid():
            application = form.save(commit=False)
            application.user = request.user
            application.save()
            total_cost = 0
            use_nums = []
            for key in request.POST.keys():
                num = key.split('_')[-1]
                if num.isdigit() and num not in use_nums:
                    product_id = int(request.POST.get(f'product_{num}'))
                    quantity = float(request.POST.get(f'number_{num}'))
                    image = request.FILES.get(f'image_{num}')
                    product = ProductWarehouse.objects.get(pk=product_id)
                    total_cost += product.product.price * quantity
                    ApplicationProduct.objects.create(
                        application=application,
                        product=product.product,
                        quantity=quantity,
                        image=image,
                        warehouse=product.warehouse,
                        city=product.city
                    )
                    use_nums.append(num)
            application.total_cost = total_cost
            application.save()

            return redirect('application:index')
    form = ApplicationForm()
    return render(request, 'application/create_application.html', {
        'form': form,
        'title': 'Формирование заказа',
        'products': ProductWarehouse.objects.all(),
    })


@login_required
def application_detail(request, app_id):
    template = 'application/application_detail.html'
    app = get_object_or_404(Application, pk=app_id)
    title = str(app)
    context = {
        'title': title,
        'app': app,
    }
    return render(request, template, context)


@login_required
def application_delete(request, app_id):
    app = get_object_or_404(Application, pk=app_id)
    if app.status != 'Создан':
        return redirect('application:app_detail', app_id=app_id)
    app.delete()
    return redirect('application:index')


@login_required
def bitrix_deals(request):
    if request.method == 'POST':
        form = ObjectsForm(request.POST, request.FILES)
        if form.is_valid():
            save_object = form.save(commit=False)
            status = check_deals_address(save_object.city, save_object.street)
            if status:
                messages.error(request, 'Такой адрес уже существует')
                return render(request, 'application/bitrix_deal.html', {
                    'form': form,
                    'title': 'Привязать объект'
                })
            data = create_deals(save_object.city, save_object.street, save_object.house,request.user.email)
            save_object.user = request.user
            save_object.save()
            messages.success(request, 'Заявка успешно создана')
            return redirect('application:create_deals')

    form = ObjectsForm()
    return render(request, 'application/bitrix_deal.html', {
        'form': form,
        'title': 'Привязать объект'
    })


class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'application/product_list.html'
    context_object_name = 'products'
    login_url = '/login/'

    def get_queryset(self):
        city = self.request.GET.get('city', '')
        warehouse = self.request.GET.get('warehouse', '')

        queryset = Product.objects.prefetch_related('stock').all()
        if city:
            queryset = queryset.filter(stock__city=city)
        if warehouse:
            queryset = queryset.filter(stock__warehouse=warehouse)

        return sorted(
            queryset,
            key=lambda x: (any(stock.in_stock == 0 for stock in x.stock.all()), x.name)
        )

templates/application/application_detail.html
{% extends 'base.html' %}
{% load static %}

{% load user_filters %}
{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/app-detail.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/product_card.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/form/style.css' %}">

</head>
    <div class="container mt-3">
        <div class="products-wrapper">
            <h1 class="title product-card-text">
                Детали заказа
            </h1>
        </div>
            <div class="card-body">
                <p class="card-text product-card-text">
                    <strong>Статус:</strong> {{ app.status }}
                </p>
                {% if app.product %}
                    <p class="card-text product-card-text">
                        <strong>Продукт/Услуга:</strong> {{ app.product }}
                    </p>
                {% endif %}
                <p class="card-text product-card-text">
                    <strong>Итоговая стоимость:</strong> {{ app.total_cost }} руб.
                </p>
                <p class="card-text product-card-text">
                    <strong>ФИО покупателя:</strong> {{ app.full_name }}
                </p>
                <p class="card-text product-card-text">
                    <strong>Номер телефона:</strong> {{ app.phone_number }}
                </p>
                <p class="card-text product-card-text">
                    <strong>Адрес доставки:</strong> {{ app.address }}
                </p>
                {% if app.production_time %}
                    <p class="card-text product-card-text">
                        <strong>Срок изготовления до:</strong> {{ app.production_time }}
                    </p>
                {% endif %}
                <p class="card-text product-card-text">
                    <strong>Создан:</strong> {{ app.created }}
                </p>
                <p class="card-text product-card-text">
                    <strong>Изменен:</strong> {{ app.updated }}
                </p>
            </div>
            <h2 class="text-center product-card-text">Состав заказа:</h2>
            <div class="scrollable-table">
                <table class="table product-card-text">
                    <thead>
                    <tr>
                        <th>Название</th>
                        <th>Количество</th>
                        <th>Город</th>
                        <th>Склад</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for app_product in app.applicationproduct_set.all %}
                        <tr>
                            <td>{{ app_product.product }}</td>
                            <td>{{ app_product.quantity }}</td>
                            <td>{{ app_product.warehouse }}</td>
                            <td>{{ app_product.city }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer text-center">
                {% if user ==  app.user and app.status == 'Создан' %}
                    <a class="btn btn-danger" href="{% url 'application:app_delete' app_id=app.pk %}">
                        Удалить заявку
                    </a>
                {% endif %}
            </div>
                
    </div>
{% endblock %}

templates/application/create_application.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<head>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'fonts/linearicons/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/form/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/create_application.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Expires" content="0" />
</head>

<div class="wrapper">
    <div class="inner-w">
            <form method="post" action="{% url 'application:app_create' %}" enctype="multipart/form-data">
                    <h3>{{ title }}</h3>
                    <div class="card-body">
                        {% load user_filters %}
                        {% if form.errors %}
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <div class="alert alert-danger">
                                        {{ error|escape }}
                                    </div>
                                {% endfor %}
                            {% endfor %}
                            {% for error in form.non_field_errors %}
                                <div class="alert alert-danger">
                                    {{ error|escape }}
                                </div>
                            {% endfor %}
                        {% endif %}
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="input-lable">
                                <label for="{{ field.id_for_label }}">
                                    {{ field.label }}
                                    {% if field.field.required %}
                                        <span class="required text-danger">*</span>
                                    {% endif %}
                                </label>
                                <div class="form-holder">
                                    <span class="{{ field.field.widget.attrs.icon_class }}"></span>
                                    {{ field|addclass:'form-control' }}
                                    {% if field.help_text %}
                                        <small class="form-text text-muted">{{ field.help_text }}</small>
                                    {% endif %}
                                </div>                             
                            </div>
                        {% endfor %}
                        <div id="product-list">
                            <div class="product">
                                <h4>Товар 1</h4>
                                <img id="image-preview_1" src="#" alt="Image Preview" style="display: none; width: 100px; height: auto;"/>
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <div class="input-lable">
                                            <label for="product_1">Название товара:</label>
                                        </div>

                                        <select name="product_1" id="product_1" class="form-control product-card" required>
                                            <option value=""> Выберите продукт</option>
                                            {% for product in products %}
                                                <option value="{{ product.id }}"
                                                        data-price="{{ product.product.price }}"
                                                        data-image-url="{{ product.product.photo.url }}">{{ product }}</option>
                                            {% endfor %}
                                        </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <div class="input-lable">
                                                
                                                <label for="number_1">Количество</label>
                                            </div>
                                            <div class="form-holder">
                                                <span class="lnr lnr-sort-amount-asc"></span>
                                                <input type="number" name="number_1" id="number_1" class="form-control"
                                                   required>
                                            </div>
                                        </div>
                                        <div class="input-lable">
                                            <span class="lnr lnr-picture"></span>
                                            <label for="image_1">Образец продукта</label>
                                        </div>
                                        <img id="file-preview_1" src="" alt="file preview 1" style="display: none; width: 100px; height: auto; margin-top: 10px; ">
                                        <div class="form-holder">
                                            <label for="image_1" class="file-label">Выберите файл</label>
                                            <input type="file" name="image_1" id="image_1" class="form-control file-input" accept=".jpg, .png" required>
                                        </div>                                    
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="btns-container">
                        <button type="submit" class="add-product">Добавить товар</button>
                        <button type="submit" class="execut-button submit-btn">Сохранить</button>
                        <h4>Предварительная цена: <span id="total-price">0 руб.</span></h4>
                    </div>
            </form>
        </div>
    </div>
    <script src="{% static 'js/application.js' %}"></script>
    <!-- <script src="{% static 'js/fileFlow.js' %}"></script> -->


{% endblock %}

templates/application/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock %}
{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/create_application.css' %}"/>

</head>
    <table class="table app-product-container">
        <thead>
            <tr>
                <th>Статус заказа</th>
                <th>Дата заказа</th>
                <th>Детали</th>
            </tr>
        </thead>
        <tbody>
            {% for app in page_obj %}
                {% include 'application/includes/application_list.html' %}
            {% empty %}
                <tr><td colspan="4">Нет заявок</td></tr>
            {% endfor %}
        </tbody>
    </table>
    {% include 'application/includes/paginator.html' %}
{% endblock %}

templates/application/product_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/product_card.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/form/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/linearicons/style.css' %}">
</head>
<div class="container mt-3">
    <div class="products-wrapper">
        <h1 class="title">Складские остатки</h1>
        <form method="get" action="{% url 'application:product-list' %}" class="form-container form-container-dark">
            <div class="form-holder">
                <span class="lnr lnr-map-marker"></span>
                <input type="text" class="form-control dark-input" placeholder="Город" name="city" value="{{ request.GET.city }}">
            </div>
            <div class="col">
                    <button type="submit" class="btn submit-btn">Фильтр</button>
            </div>
        </form>
    </div>

    </form>
    <div class="row mt-3">
        {% for product in products %}
        <div class="col-md-4 mb-4" >
            <div class="card mb-4 box-shadow product-card-container">
                <div class="img-container">
                {% if product.photo %}
                <img class="card-img-top" src="{{ product.photo.url }}" alt="{{ product.name }}">
                {% else %}
                <img class="card-img-top" src="{% static 'no_image_available.png' %}" alt="No image available">
                {% endif %}
            </div>
                <div class="card-body product-card">
                    <div>
                        <h5 class="card-title product-card-text">{{ product.name }}</h5>
                        <p class="card-text product-card-text">{{ product.description|default:"" }}</p>
                    </div>

                    {% for stock in product.stock.all %}
                    <div class="mt-2">
                        <div class="product-card-text">{{ stock.city }} - {{ stock.warehouse }}</div>
                        <div class="d-flex justify-content-between align-items-center">
                            {% if stock.in_stock > 0 %}
                                <div class="badge badge-success">
                                    Остаток: {{ stock.in_stock }} {{ product.unit }}
                                </div>
                            {% else %}
                                <div class="badge badge-danger">
                                    Под заказ
                                </div>
                            {% endif %}
                            <small class="product-card-text product-card-price">{{ product.price }} руб./{{ product.unit }}</small>
                        </div>
                    </div>
                    {% empty %}
                    <div class="mt-2"><span class="badge badge-secondary">No stock info</span></div>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}