application/urls.py
from django.urls import path

from . import views

app_name = 'application'

urlpatterns = [
    path('', views.index),
    path('index.html', views.index, name='index'),
    path('application/<int:app_id>/', views.application_detail, name='app_detail'),
    path('create/', views.application_create, name='app_create'),
    path('app/<int:app_id>/delete/', views.application_delete, name='app_delete'),
    path('create_deals/', views.bitrix_deals, name='create_deals'),
    path('products/', views.ProductListView.as_view(), name='product-list'),

]

config/urls.py
from django.urls import path, include

from config import settings
from application.admin import bot_admin
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('admin/', bot_admin.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('', include('application.urls', namespace='application')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, \
    LoginView, PasswordChangeDoneView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy

from users.forms import CustomLoginForm

from . import views
from .views import CustomPasswordResetView

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(
        template_name='users/logged_out.html'), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change_form.html',
        success_url=reverse_lazy('users:password_change_done')),
         name='password_change_form'),
    path('login/', LoginView.as_view(
        template_name='users/login.html',
        authentication_form=CustomLoginForm
        ),
         name='login'
         ),
    path('password_reset/', CustomPasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        success_url=reverse_lazy('users:password_reset_done')
    ),
         name='password_reset_form'
         ),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
         name='password_change_done'
         ),
    path('password_rest/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
         name='password_reset_done'
         ),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy(
            'users:password_reset_complete')),
         name='password_reset_confirm'
         ),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
         name='password_reset_complete'
         ),
]

templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:red">Bot</span>tec</p>

templates/includes/header.html
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
</head>
<nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
            <img src="{% static 'img/logo.png' %}" alt="Logo" style="height: 60px;">
        {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'application:index' %}">Пользователь: {{ user.first_name }}</a>
        {% endif %}
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                {% with request.resolver_match.view_name as view_name %}
                    {% if user.is_authenticated %}
                        <li class="nav-item rounded">
                            <a class="nav-link" href="{% url 'users:logout' %}">
                                Выйти
                            </a>
                        </li>
                    {% else %}
                        <li class="nav-item rounded">
                            <a class="nav-link" href="{% url 'users:login' %}">
                                Войти
                            </a>
                        </li>
                        <li class="nav-item rounded">
                            <a class="nav-link" href="{% url 'users:signup' %}">
                                Регистрация
                            </a>
                        </li>
                    {% endif %}
                {% endwith %}
            </ul>
        </div>
    </div>
</nav>

templates/includes/side-bar.html
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/side_bar.css' %}">
</head>
<input type="checkbox" id="nav-toggle" hidden>
<nav class="nav">
    <label for="nav-toggle" class="nav-toggle" onclick></label>
    <h2 class="logo"> 
        <a  href="{% url 'application:index' %}"><img src="{% static 'img/logo.png' %}" alt="Logo" style="height: 60px;">
        </a> 
    </h2>
    <ul>
        {% if user.is_staff %}
        <li><a href="{% url 'admin:index' %}">
                Админ панель</a>
        </li>
        {% endif %}
        <li><a  href="{% url 'application:index' %}">
            Заявки</a>
        <li><a  href="{% url 'application:app_create' %}">
            Создать заявку</a>
        <li><a href="{% url 'application:create_deals' %}">
            Привязать объект</a>
        <li><a href="{% url 'application:product-list' %}">
            Складские остатки</a>
        <li><a href="{% url 'users:password_change_form' %}">
            Изменить пароль</a>
        <li><a href="{% url 'users:logout' %}">
            Выйти</a>
    </ul>

</nav>
 