config/urls.py
from django.urls import path, include

from config import settings
from application.admin import bot_admin
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('admin/', bot_admin.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('', include('application.urls', namespace='application')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, \
    LoginView, PasswordChangeDoneView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy

from users.forms import CustomLoginForm

from . import views
from .views import CustomPasswordResetView

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(
        template_name='users/logged_out.html'), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change_form.html',
        success_url=reverse_lazy('users:password_change_done')),
         name='password_change_form'),
    path('login/', LoginView.as_view(
        template_name='users/login.html',
        authentication_form=CustomLoginForm
        ),
         name='login'
         ),
    path('password_reset/', CustomPasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        success_url=reverse_lazy('users:password_reset_done')
    ),
         name='password_reset_form'
         ),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
         name='password_change_done'
         ),
    path('password_rest/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
         name='password_reset_done'
         ),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy(
            'users:password_reset_complete')),
         name='password_reset_confirm'
         ),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
         name='password_reset_complete'
         ),
]

users/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, AbstractUser, Group, Permission
from django.db import models
from django.utils.crypto import get_random_string


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('Пользователь с таким email же существует')
        username = get_random_string(20)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):
    email = models.CharField(verbose_name='Адрес электронной почты', max_length=255, unique=True)
    # groups = models.ManyToManyField(Group, related_name="customuser_set")
    username = models.CharField(
        blank=True,
        null=True,
        max_length=100
    )
    user_permissions = models.ManyToManyField(
        Permission,
        related_name="customuser_set",
        blank=True,
        null=True
    )
    objects = CustomUserManager()
    status = models.BooleanField(
        default=False,
        verbose_name='Подтвержден/Не подтвержден'
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def clean(self):
        setattr(self, self.USERNAME_FIELD, self.normalize_username(self.get_username()))
        self.email = self.email

    @property
    def is_active(self):
        return self.is_superuser or self.status

users/forms.py
from django.contrib.auth.forms import (
    UserCreationForm,
    AuthenticationForm,
    PasswordResetForm
)
from django import forms

from users.models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'lnr lnr-user form-control',
            'placeholder': 'Имя',
            'icon_class': 'lnr lnr-user'
        }
    ))
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'lnr lnr-user form-control',
            'placeholder': 'Фамилия',
            'icon_class': 'lnr lnr-user'
        }
    ))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={
            'class': 'lnr lnr-envelope form-control',
            'placeholder': 'Электронная почта',
            'icon_class': 'lnr lnr-envelope'
        }
    ))
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'lnr lnr-lock form-control',
            'placeholder': 'Пароль',
            'icon_class': 'lnr lnr-lock'
        }
    ))
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'lnr lnr-lock form-control',
            'placeholder': 'Подтверждение пароля',
            'icon_class': 'lnr lnr-lock'
        }
    ))

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2')


class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.EmailInput(
        attrs={
            'class': 'lnr lnr-envelope form-control',
            'placeholder': 'Email',
            'type': 'email',
            'icon_class': 'lnr lnr-envelope'
        }
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'lnr lnr-lock form-control',
            'placeholder': 'Пароль',
            'type': "password",
            'icon_class': 'lnr lnr-lock'
        }
    ))


class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={
            'class': 'lnr lnr-envelope form-control',
            'placeholder': 'Электронная почта',
            'icon_class': 'lnr lnr-envelope'
        }
    ))

users/views.py
from django.contrib.auth.views import PasswordResetView
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CustomPasswordResetForm, CustomUserCreationForm


class SignUp(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('application:index')
    template_name = 'users/signup.html'


class CustomPasswordResetView(PasswordResetView):
    form_class = CustomPasswordResetForm
    email_template_name = "users/password_reset_email.html"

templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">
                Выход
            </div>
            <div class="card-body">
                <p>
                    Вы вышли из своей учётной записи. Ждём вас снова!
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/users/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
<head>
    <link rel="stylesheet" href="{% static 'fonts/linearicons/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/form/style.css' %}">
</head>

    <div class="wrapper">
        <div class="inner">
            <div >
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            {{ error|escape }}
                        </div>
                    {% endfor %}
                {% endif %}

                <form method="post"
                      {% if action_url %}
                      action="{% url action_url %}"
                      {% endif %}
                >
                    {% csrf_token %}
                    <h3>
                        Авторизация
                    </h3>
                    {% for field in form %}
                    <div class="form-holder">
                        <span class="{{ field.field.widget.attrs.icon_class }}"></span>
                        {{ field|addclass:'form-control' }}
                    </div>
                    {% endfor %}
                    <div class="btns-container">
                        <button type="submit" class="execut-button submit-btn">
                            <span>Войти</span>
                        </button>
                        <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
                            Забыли пароль?
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card main-content">
                <div class="card-header">
                    Пароль изменён
                </div>
                <div class="card-body">
                    <p>Пароль изменён успешно</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/users/password_change_form.html
{% extends "base.html" %}
{% load static %}

{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
<head>
    <link rel="stylesheet" href="{% static 'fonts/linearicons/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/form/style.css' %}">
</head>
<div class="wrapper">
    <div class="inner">
            <div class="card-body">
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            {{ error|escape }}
                        </div>
                    {% endfor %}
                {% endif %}
                <form method="post"
                      {% if action_url %}
                      action="{% url action_url %}"
                      {% endif %}
                >
                    {% csrf_token %}
                    <h3>
                        Замена пароля
                    </h3>
                    {% for field in form %}
                        <div class="form-group row my-3"
                             {% if field.field.required %}
                                aria-required="true"
                             {% else %}
                                aria-required="false"
                             {% endif %}
                        >
                        <div class="input-lable">
                            <label for="{{ field.id_for_label }}">
                                {{ field.label }}
                                {% if field.field.required %}
                                    <span class="required text-danger">*</span>
                                {% endif %}
                            </label>
                        </div>
                            <div>
                                <div class="form-holder">
                                    <span class="lnr lnr-lock"></span>
                                    {{ field|addclass:'form-control' }}
                                </div>                                {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                        {{ field.help_text|safe }}
                                    </small>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary submit-btn">
                            Изменить пароль
                        </button>
                    </div>
                </form>
            </div>
    </div>
</div>
{% endblock %}

templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">
                    Восстановление пароля завершено
                </div>
                <div class="card-body">
                    <p>Ваш пароль был сохранен. Используйте его для входа</p>
                    <a href="{% url 'users:login' %}">Войти</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
{% load user_filters %}

{% if validlink %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">
                    Войти на сайт
                </div>
                <div class="card-body">
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    {{ error|escape }}
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endif %}
                    <form method="post"
                          {% if action_url %}
                            action="{% url action_url %}"
                          {% endif %}
                    >
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group row my-3"
                                 {% if field.field.required %}
                                    aria-required="true"
                                 {% else %}
                                    aria-required="false"
                                 {% endif %}
                            >
                                <label for="{{ field.id_for_label }}">
                                    {{ field.label }}
                                    {% if field.field.required %}
                                        <span class="required text-danger">*</span>
                                    {% endif %}
                                </label>
                                <div>
                                    {{ field|addclass:'form-control' }}
                                    {% if field.help_text %}
                                        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                            {{ field.help_text|safe }}
                                        </small>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                Назначить новый пароль
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% else %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">Ошибка</div>
                <div class="card-body">
                    <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
                </div>
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}

templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card main-content form-container">
                <div class="card-header">
                    Отправлено письмо
                </div>
                <div class="card-body">
                    <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

templates/users/password_reset_form.html
{% extends "base.html" %}
{% load static %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
<head>
    <link rel="stylesheet" href="{% static 'fonts/linearicons/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/form/style.css' %}">
</head>

<div class="wrapper">
    <div class="inner">
        <div class="card-body">
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            {{ error|escape }}
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ error|escape }}
                    </div>
                {% endfor %}
            {% endif %}
            <form method="post"
                    {% if action_url %}
                    action="{% url action_url %}"
                    {% endif %}
            >
                {% csrf_token %}
                <h3>Забыли пароль?</h3>
                <p>Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
                </p>
                {% for field in form %}
                    <div class="form-group row my-3"
                            {% if field.field.required %}
                            aria-required="true"
                            {% else %}
                            aria-required="false"
                            {% endif %}
                    >
                            <div>
                            <div class="form-holder">
                                <span class="{{ field.field.widget.attrs.icon_class }}"></span>
                                {{ field|addclass:'form-control' }}
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <div class="btns-container">
                    <button type="submit" class="execut-button submit-btn">
                        <span>Сбросить пароль</span>
                    </button>
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/users/signup.html
{% extends "base.html" %}
{% load static %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'fonts/linearicons/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/form/style.css' %}">
</head>
    <div class="wrapper">
        <div class="inner">
            <div class="card-body">
                {% load user_filters %} {# Загружаем фильтры #}
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            {{ error|escape }}
                        </div>
                    {% endfor %}
                {% endif %}

                <form method="post" action="{% url 'users:signup' %}">
                    {% csrf_token %}
                    <h3>Регистрация</h3>

                    {% for field in form %}
                        <div class="form-holder">
                            <span class="{{ field.field.widget.attrs.icon_class }}"></span>
                            {{ field|addclass:'form-control' }}
                            {% if field.help_text %}
                                <small class="form-text text-muted">{{ field.help_text }}</small>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <div class="btns-container">
                        <button type="submit" class="execut-button submit-btn">
                            <span>Зарегистрироваться</span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}